apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend
  namespace: dev
  labels:
    role: backend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      role: backend
  template:
    metadata:       
     labels:
       role: backend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: backend
        image: 011528285175.dkr.ecr.us-east-1.amazonaws.com/palaymoundekar/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3500
        env:
        - name: host
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: host
        - name: user
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: user
        - name: password
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: password
        - name: database
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: database


